language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

script:
    - platformio run
    - platformio test -e local --verbose
